name: Release

on:
  push:
    tags:
      - 'v*.*.*'  # Triggers on version tags (e.g., v1.0.0, v2.1.0)

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.22'  # Specify your Go version

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      - name: Generate Changelog
        run: |
          git fetch --tags
          # Generate a changelog from commit messages
          git log $(git describe --tags --abbrev=0)..HEAD --pretty=format:"* %s" > CHANGELOG.md

      - name: Commit Changelog
        if: github.ref_type == 'tag'
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "actions@github.com"
          git add CHANGELOG.md
          git commit -m "chore(release): Update changelog for ${GITHUB_REF#refs/tags/}"
          git push

      - name: Set Release Version Environment Variable
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
